title: osxi
email: zach@poeticsystems.com
description: >
  My collection of hopefully useful articles
baseurl: ""
url: "http://osxi.github.io"
twitter_username: osxi_was_taken
github_username:  osxi
markdown: kramdown
